services:

# FUSIONAUTH

  db:
    image: postgres:16.0-bookworm
    container_name: faDb
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - db_net
    volumes:
      - db_data:/var/lib/postgresql/data

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    container_name: fa
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_ROOT_USERNAME: ${POSTGRES_USER}
      DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      FUSIONAUTH_APP_INSTALLATION_SOURCE: fusionauth-quickstart-php-drupal-web
      FUSIONAUTH_APP_KICKSTART_FILE: ${FUSIONAUTH_APP_KICKSTART_FILE}
      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_APP_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: ${FUSIONAUTH_APP_RUNTIME_MODE}
      FUSIONAUTH_APP_URL: http://fusionauth:9011
      SEARCH_TYPE: database
    networks:
      - db_net
    ports:
      - 9011:9011
    volumes:
      - fusionauth_config:/usr/local/fusionauth/config
      - ./kickstart:/usr/local/fusionauth/kickstart

# DRUPAL

  web:
    image: drupal:php8.2-apache-bullseye
    container_name: drupal
    volumes:
      - ./complete-application:/opt/drupal:cached
    ports:
      - "80:80"
    networks:
      - db_net
    extra_hosts:
      - host.docker.internal:host-gateway

  db2:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_TCP_PORT: 3307
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupaldb
      MYSQL_USER: drupal
      MYSQL_PASSWORD: verybadpassword
    ports:
      - "3307:3307"
    networks:
      - db_net

networks:
  db_net:
    driver: bridge

volumes:
  db_data:
  fusionauth_config: