FROM fusionauth/fusionauth-app:latest
ARG DATABASE_HOST
ARG DATABASE_NAME
ARG POSTGRES_PASSWORD
ARG POSTGRES_USER
ARG FUSIONAUTH_APP_RUNTIME_MODE
ARG DATABASE_USERNAME
LABEL description="Create an image running FusionAuth App. Installs FusionAuth App"
LABEL maintainer="FusionAuth <dev@fusionauth.io>"
EXPOSE 9011
USER fusionauth
ENV FUSIONAUTH_USE_GLOBAL_JAVA=1
ENV JAVA_HOME=/opt/openjdk
ENV PATH=$PATH:$JAVA_HOME/bin
ENV DATABASE_URL=jdbc:postgresql://$DATABASE_HOST.oregon-postgres.render.com/$DATABASE_NAME
ENV DATABASE_USERNAME=$POSTGRES_USER
ENV DATABASE_PASSWORD=$POSTGRES_PASSWORD
ENV DATABASE_ROOT_USERNAME=$DATABASE_USERNAME
ENV DATABASE_ROOT_PASSWORD=$POSTGRES_PASSWORD
ENV FUSIONAUTH_APP_RUNTIME_MODE=$FUSIONAUTH_APP_RUNTIME_MODE
CMD ["/usr/local/fusionauth/fusionauth-app/bin/start.sh"]